### ISSUE TITLE
How to generator model without "public" prefix and Query include in model

### ISSUE THREAD

**Issue by kimthangatm** [ozum/sequelize-pg-generator#1]
Hello, i have a question:

**1. How to generator model without "public"**
public.categories => categories
public.users => users

**2. When include use**r:  include : [{model : db.model('public.users')}] error **`Possibly unhandled Error: public.users is not associated to public.categories!`**
```javascript
    let config = require('../../libs/config');
    let db = require('../../libs/models_old/index');
    db.setup(config.db.database, config.db.username, config.db.password, config.db);

    let categories = db.model('public.categories');
    categories.findAll({
        include : [{model : db.model('public.users')}]
    }).then(function (result) {
        res.send(result);
    });
```
Models auto generator, 2 table with FK

In public_categories
```javascript
{
        type: "belongsTo",
        model: "public.users",
        schema: "public",
        table: "users",
        source: "generator",
        details: {
            as: "user",
            foreignKey: "user_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }
```

In public_users

```javascript
relations: [{
        type: "hasMany",
        model: "public.categories",
        schema: "public",
        table: "categories",
        source: "generator",
        details: {
            as: "categoriesFkUsersIds",
            foreignKey: "user_id",
            onDelete: "NO ACTION",
            onUpdate: "NO ACTION"
        }
    }
```

**Comment by ozum** [comment]
**1. How to generator model without "public"**

It is already written in documentation:
https://www.npmjs.com/package/sequelize-pg-generator#no-schema-prefix

**2. When include user:** include : [{model : db.model('public.users')}] error Possibly unhandled Error: public.users is not associated to public.categories!**

sequelize-pg-generator sets up relations with an "as". Otherwise multiple relations between same two tables collides. For example:
account has many contacts as primaryContacts (account -----< contact)
account has many contacts as secondaryContacts (account ----< contact)

In this case sequelize.js requires you to specify "as" alias in the "as" attribute during eager loading.

    var orm = require('./model');
    orm.setup(testDB.dbConfig.database, testDB.dbConfig.user, testDB.dbConfig.password, { host: testDB.dbConfig.host, logging: false});
    var sequelize = orm.sequelize;
    account = orm.model('public.account'); // Can be configured without schema.
    contact = orm.model('public.contact'); // Can be configured without schema.
    account.findAll({ include: [ { model: contact, as: "primaryContacts" } ] }).then(function(data) {
        console.log(data[0].primaryContacts[0].name);
    });

In your case 

    let categories = db.model('public.categories');
    let users = db.model('public.users');

    categories.findAll({
        include : [{model : users, as: "user"}]  // taken from public_categories.details.as
    }).then(function (result) {
        res.send(result);
    });

I added a test file called test/usage.js and added this case into it.
