### ISSUE TITLE
defaultScope with includes

### ISSUE THREAD

**Issue by prokoptsev** [ozum/sequelize-pg-generator#2]
Hi. Could you tell how I can use `defaultScope` options with `include` by generated models?

**Comment by ozum** [comment]
Hi,

Please use pg-generator module instead of this one. It's successor of this module. [pg-generator's sequelize module](http://www.pg-generator.com/builtin-templates/sequelize/) produces higher quality direct code from its templates. You can modify how code is generated by altering it's templates.
