### ISSUE TITLE
ClearDefaultValue function work not correctly with Default value is uuid_generate_v1

### ISSUE THREAD

**Issue by PhiNguyen1991** [ozum/sequelize-pg-generator#4]
When I'm working with postgresDB, i've set default value is uuid_generate_v1 up to my column . then I generate ORM.
[Actual]:  My column I set default value before didn't have in ORM generated.
[Expect]: it should have : defaultValue: Seq.UUIDV1

**Comment by ozum** [comment]
@PhiNguyen1991, please use [pg-generator](http://www.pg-generator.com/) instead of this module as written in README.

Both `sequelize-pg-generator` and `pg-generator` does not generate default values well, because it is impossible to cover every case. (i.e. SQL functions or complex SQL syntax may be used in default values. They cannot be represented in JavaScript and ORMs.)

However, if you use `pg-generator`, you can modify template according to your needs and cover your use case for default values.

**Comment by PhiNguyen1991** [comment]
Hi @ozum , because my project are using sequelize-pg-generator, 
So that, I use definition-files-custom for custom the ORM when it load. 
**ex: util.setDefaultValue('id', Seq.UUIDV1);**
Thanks
